- README.rst
> Update document by adding pipy support and helper functions for rdklibtest

- README.rst
> add InvalidParametersError import in the documentation

- .github/workflows/ci.yml
- setup.py
- template.yaml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Add Python 3.7 3.8 as supported

- README.rst
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Add GH build badge to README

- README.rst
*Issue #, if available:* #6
*Description of changes:* Review the name of the variable and order in the documentation.
> update doc for Evaluation()

- .github/workflows/ci.yml
- rdklib/__init__.py
- rdklib/configrule.py
- rdklib/evaluator.py
- rdklib/util/service.py
- tst/test/rdklib_configrule_test.py
- tst/test/rdklib_evaluator_test.py
- tst/test/rdklib_util_service_test.py
> add resource type in Evaluator

- rdklib_addon_to_rdk_workshop/README.md
The **RDKlib Add-On** has the objective to take the same example, MFA_ENABLED_RULE created in the **RDK Workshop**, and provide guidance on how to accomplish the solution using the [RDKLib](https://github.com/awslabs/aws-config-rdklib) Python library to enable you to **run custom AWS Config Rules at scale**.
> RDKlib Add-On to RDK Workshop

- template.yaml
> output rdklib layer ARN

- rdklib/__init__.py
- template.yaml
* Update python package version classifiers and fix styling for pep8 by @mbeacom in https://github.com/awslabs/aws-config-rdklib/pull/39
* Fix #28 - Resolve typos in README.rst by @mbeacom in https://github.com/awslabs/aws-config-rdklib/pull/37
* Remove remaining 3.6 python references by @mbeacom in https://github.com/awslabs/aws-config-rdklib/pull/40
_Please note:  The above changelog was generated by GitHub._
> RELEASE 0.3.0

- .github/workflows/publish_cft.yaml
Gives the CFT auto-expand permissions so it can update lambda layers
> give autoexpand permissions

- .github/workflows/publish_cft.yaml
- samconfig.toml
- template.yaml
> create new branch for workflow

- .github/workflows/publish_cft.yaml
> Update region in workflow

- .github/workflows/publish_cft.yaml
Adds workflow steps to make the published lambda layers public
> Public layer

- .github/workflows/publish_cft.yaml
- .gitignore
- poetry.lock
- pyproject.toml
- rdklibtest/test.py
- template.yaml
Restructures how the Lambda Layer is packaged so that it contains the correct contents
> Restructure source for lambda layer package

- rdklib/util/service.py
N/A
Adds logic for a fallback for resourceName if not populated.
> Add fallback for ResourceName if not populated

- pyproject.toml
- rdklib/__init__.py
- template.yaml
> version bump to 0.3.2

- .github/workflows/publish_cft.yaml
> Trigger CFT publish on master push

- .github/workflows/publish_cft.yaml
Because these are already included in the Lambda runtime, they should not be included in the layer packaging.
> Don't package boto3 or botocore

- .github/workflows/publish_cft.yaml
- rdklib/evaluation.py
#31 
Adds a simple repr() method so that `Evaluation`s can be printed with useful data.
> Add repr method for Evaluation class

- .github/actions/dep-setup/action.yml
- .github/workflows/pytest.yml
Some routine hygiene to keep the repo updated
> use v4 of cache, and update poetry's lock file

- .github/workflows/publish_cft.yaml
another little change required by poetry 2.x
> Include plugin export
